# Grafana datasource provisioning for InfluxDB
# https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources

apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: hwtest
      defaultBucket: telemetry
      tlsSkipVerify: true
    secureJsonData:
      token: hwtest-dev-token
    isDefault: true
    editable: true
